
#pragma once

#define MSDFGEN_PUBLIC //${MSDFGEN_PUBLIC_MACRO_VALUE}
#define MSDFGEN_EXT_PUBLIC //${MSDFGEN_PUBLIC_MACRO_VALUE}

//${MSDFGEN_ADDITIONAL_DEFINES}
#define MSDFGEN_STANDALONE
#define MSDFGEN_EXTENSIONS
#define MSDFGEN_DISABLE_SVG
#define MSDFGEN_USE_LIBPNG
